require:
  - rubocop-performance
  # - rubocop-rspec   # If using RSpe

AllCops:
  DisabledByDefault: true

Performance:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/SpaceAroundOperators:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: separator
  EnforcedColonStyle: separator
  EnforcedLastArgumentHashStyle: always_ignore

Style/BlockDelimiters:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/SymbolArray:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: true

