plugins: 
  - rubocop-performance

AllCops:
  DisabledByDefault: true

Performance:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentationConsistency:
  Enabled: true

Layout/EmptyLines:
  Enabled: true
 
Layout/MultilineMethodCallIndentation:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true


Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_ignore

Style/WhenThen:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/SymbolArray:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: true

